local Library = loadstring(game:HttpGet("https://pastebin.com/raw/vff1bQ9F"))()
local Window = Library.CreateLib("Name", "Midnight")
local Tab = Window:NewTab("Lt2")
local Section = Tab:NewSection("Main Nitrogen")
Section:NewButton("Nitrogen Lt2", "ButtonInfo", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/Butterisgood/Butter/main/Root2.lua'))("")
    print("Clicked")
end)
